"use client";

import type { Theme } from "mind-elixir";

export const DEFAULT_THEME_NAME = "Default";

export const MIND_THEMES: Theme[] = [
  {
    name: "Inkline",
    type: "light",
    palette: ["#111827", "#1f2937", "#374151", "#6b7280", "#9ca3af"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#0f172a",
      "--main-bgcolor": "#f7f7f8",
      "--color": "#0f172a",
      "--bgcolor": "#ffffff",
      "--selected": "#0f172a",
      "--accent-color": "#111827",
      "--root-color": "#ffffff",
      "--root-bgcolor": "#0f172a",
      "--root-border-color": "#0f172a",
      "--root-radius": "14px",
      "--main-radius": "10px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#111827",
      "--panel-bgcolor": "#ffffff",
      "--panel-border-color": "#e5e7eb",
      "--map-padding": "40px",
    },
  },
  {
    name: "Blueprint",
    type: "light",
    palette: ["#1e3a8a", "#2563eb", "#38bdf8", "#0ea5e9", "#7dd3fc"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#1e3a8a",
      "--main-bgcolor": "#f5f9ff",
      "--color": "#0f172a",
      "--bgcolor": "#eaf3ff",
      "--selected": "#1d4ed8",
      "--accent-color": "#2563eb",
      "--root-color": "#f8fafc",
      "--root-bgcolor": "#1e3a8a",
      "--root-border-color": "#1e3a8a",
      "--root-radius": "14px",
      "--main-radius": "10px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#0f172a",
      "--panel-bgcolor": "#f8fbff",
      "--panel-border-color": "#c7d2fe",
      "--map-padding": "40px",
    },
  },
  {
    name: "Paper + Pencil",
    type: "light",
    palette: ["#3f3f46", "#52525b", "#71717a", "#a1a1aa", "#d4d4d8"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#3f3f46",
      "--main-bgcolor": "#fbf7f0",
      "--color": "#2f2f2f",
      "--bgcolor": "#f6f1e7",
      "--selected": "#3b3b3b",
      "--accent-color": "#a16207",
      "--root-color": "#fffaf0",
      "--root-bgcolor": "#3f3f46",
      "--root-border-color": "#3f3f46",
      "--root-radius": "14px",
      "--main-radius": "10px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#2f2f2f",
      "--panel-bgcolor": "#fbf7f0",
      "--panel-border-color": "#e7dccf",
      "--map-padding": "40px",
    },
  },
  {
    name: "Mono Dark",
    type: "dark",
    palette: ["#e5e7eb", "#cbd5f5", "#94a3b8", "#64748b", "#475569"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#e5e7eb",
      "--main-bgcolor": "#111827",
      "--color": "#e5e7eb",
      "--bgcolor": "#0b0f14",
      "--selected": "#f9fafb",
      "--accent-color": "#93c5fd",
      "--root-color": "#0b0f14",
      "--root-bgcolor": "#e5e7eb",
      "--root-border-color": "#e5e7eb",
      "--root-radius": "14px",
      "--main-radius": "10px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#e5e7eb",
      "--panel-bgcolor": "#111827",
      "--panel-border-color": "#1f2937",
      "--map-padding": "40px",
    },
  },
  {
    name: "Glass Pastel",
    type: "light",
    palette: ["#a5b4fc", "#f9a8d4", "#67e8f9", "#86efac", "#fde68a"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#5b6270",
      "--main-bgcolor": "rgba(255,255,255,0.75)",
      "--color": "#3f3f46",
      "--bgcolor": "#f6f5ff",
      "--selected": "#4f46e5",
      "--accent-color": "#8b5cf6",
      "--root-color": "#ffffff",
      "--root-bgcolor": "#4f46e5",
      "--root-border-color": "#4f46e5",
      "--root-radius": "14px",
      "--main-radius": "12px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#374151",
      "--panel-bgcolor": "rgba(255,255,255,0.9)",
      "--panel-border-color": "#e5e7eb",
      "--map-padding": "40px",
    },
  },
  {
    name: "Museum",
    type: "light",
    palette: ["#3a2f25", "#6b4b2a", "#8b5e34", "#b08968", "#dcc4a5"],
    cssVar: {
      "--node-gap-x": "22px",
      "--node-gap-y": "18px",
      "--main-gap-x": "26px",
      "--main-gap-y": "22px",
      "--main-color": "#3a2f25",
      "--main-bgcolor": "#fbf6ee",
      "--color": "#3a2f25",
      "--bgcolor": "#f5efe6",
      "--selected": "#8b5e34",
      "--accent-color": "#b45309",
      "--root-color": "#fdf6ec",
      "--root-bgcolor": "#3a2f25",
      "--root-border-color": "#3a2f25",
      "--root-radius": "14px",
      "--main-radius": "10px",
      "--topic-padding": "6px 14px",
      "--panel-color": "#3a2f25",
      "--panel-bgcolor": "#fbf6ee",
      "--panel-border-color": "#e7dccf",
      "--map-padding": "40px",
    },
  },
];

export const MIND_THEME_BY_NAME = Object.fromEntries(
  MIND_THEMES.map((theme) => [theme.name, theme])
);

export const MIND_THEME_OPTIONS = [
  { name: DEFAULT_THEME_NAME },
  ...MIND_THEMES,
];

export const MIND_THEME_PRESETS = [
  {
    name: DEFAULT_THEME_NAME,
    description: "기본 테마",
    theme: undefined as Theme | undefined,
  },
  {
    name: "Inkline",
    description: "검은 선, 미니멀한 느낌",
    theme: MIND_THEME_BY_NAME["Inkline"],
  },
  {
    name: "Blueprint",
    description: "청색 도면 스타일",
    theme: MIND_THEME_BY_NAME["Blueprint"],
  },
  {
    name: "Paper + Pencil",
    description: "스케치 감성의 종이 톤",
    theme: MIND_THEME_BY_NAME["Paper + Pencil"],
  },
  {
    name: "Mono Dark",
    description: "고대비 다크 모드",
    theme: MIND_THEME_BY_NAME["Mono Dark"],
  },
  {
    name: "Glass Pastel",
    description: "부드러운 파스텔 톤",
    theme: MIND_THEME_BY_NAME["Glass Pastel"],
  },
  {
    name: "Museum",
    description: "전시 아카이브 느낌",
    theme: MIND_THEME_BY_NAME["Museum"],
  },
];
